name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      attest-package:
        description: "Create GitHub provenance attestation for the package."
        default: "false"
        type: string
    outputs:
      artifact-name:
        description: "Name of the uploaded artifact; use for artifact retrieval."
        value: ${{ jobs.package.outputs.artifact-name }}

# Cancel active CI runs for a PR before starting another run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Read-only by default. Called reusable workflows and individual jobs
# declare any additional permissions they require.
permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: "1"

jobs:
  pre-commit:
    name: Pre-commit checks
    permissions: {}
    uses: beeware/.github/.github/workflows/pre-commit-run.yml@741cc5a311012ee0ee195938889a337449d01eeb  # main
    with:
      pre-commit-source: "--group pre-commit"

  towncrier:
    name: Check towncrier
    permissions: {}
    uses: beeware/.github/.github/workflows/towncrier-run.yml@741cc5a311012ee0ee195938889a337449d01eeb  # main
    with:
      tox-source: "--group tox-uv"

  package:
    name: Package Toga-Chart
    permissions:
      id-token: write
      contents: read
      attestations: write
    uses: beeware/.github/.github/workflows/python-package-create.yml@741cc5a311012ee0ee195938889a337449d01eeb  # main
    with:
      attest: ${{ inputs.attest-package }}

  unit-tests:
    name: Python compatibility test
    needs: [ pre-commit, towncrier, package ]
    runs-on: macos-latest
    permissions:
      contents: read
      actions: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Get packages
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        name: ${{ needs.package.outputs.artifact-name }}
        path: dist

    - name: Install Tox
      run: python -m pip install --group tox-uv

    - name: Test
      run: tox -e py --installpkg dist/toga_chart-*.whl
