name: Dependabot Change Note

on:
  push:
    branches:
      - 'dependabot/**'

jobs:
  changenote:
    permissions: {}
    name: Dependabot Change Note
    uses: beeware/.github/.github/workflows/dependabot-changenote.yml@main
    secrets:
      BRUTUS_PAT_TOKEN: ${{ secrets.BRUTUS_PAT_TOKEN }}
